/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FornecedorRouteImport } from './routes/fornecedor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoIndexRouteImport } from './routes/recebimento/index'
import { Route as QuebraIndexRouteImport } from './routes/quebra/index'
import { Route as ExpedicaoIndexRouteImport } from './routes/expedicao/index'
import { Route as RecebimentoValesRouteImport } from './routes/recebimento/vales'
import { Route as RecebimentoLiberacoesRouteImport } from './routes/recebimento/liberacoes'
import { Route as RecebimentoFaltasRouteImport } from './routes/recebimento/faltas'
import { Route as RecebimentoConferirRouteImport } from './routes/recebimento/conferir'
import { Route as QuebraLancarRouteImport } from './routes/quebra/lancar'
import { Route as GestaoUsuariosRouteImport } from './routes/gestao.usuarios'
import { Route as ExpedicaoTvRouteImport } from './routes/expedicao/tv'
import { Route as CaixasSaldoRouteImport } from './routes/caixas/saldo'
import { Route as CaixasRetornoRouteImport } from './routes/caixas/retorno'
import { Route as CaixasInventarioRouteImport } from './routes/caixas/inventario'
import { Route as CaixasGalpaoRouteImport } from './routes/caixas/galpao'
import { Route as CaixasFornecedorRouteImport } from './routes/caixas/fornecedor'
import { Route as CaixasEconomiaRouteImport } from './routes/caixas/economia'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorRoute = FornecedorRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIndexRoute = RecebimentoIndexRouteImport.update({
  id: '/recebimento/',
  path: '/recebimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuebraIndexRoute = QuebraIndexRouteImport.update({
  id: '/quebra/',
  path: '/quebra/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicaoIndexRoute = ExpedicaoIndexRouteImport.update({
  id: '/expedicao/',
  path: '/expedicao/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoValesRoute = RecebimentoValesRouteImport.update({
  id: '/recebimento/vales',
  path: '/recebimento/vales',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoLiberacoesRoute = RecebimentoLiberacoesRouteImport.update({
  id: '/recebimento/liberacoes',
  path: '/recebimento/liberacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoFaltasRoute = RecebimentoFaltasRouteImport.update({
  id: '/recebimento/faltas',
  path: '/recebimento/faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoConferirRoute = RecebimentoConferirRouteImport.update({
  id: '/recebimento/conferir',
  path: '/recebimento/conferir',
  getParentRoute: () => rootRouteImport,
} as any)
const QuebraLancarRoute = QuebraLancarRouteImport.update({
  id: '/quebra/lancar',
  path: '/quebra/lancar',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoUsuariosRoute = GestaoUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GestaoRoute,
} as any)
const ExpedicaoTvRoute = ExpedicaoTvRouteImport.update({
  id: '/expedicao/tv',
  path: '/expedicao/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasSaldoRoute = CaixasSaldoRouteImport.update({
  id: '/caixas/saldo',
  path: '/caixas/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasRetornoRoute = CaixasRetornoRouteImport.update({
  id: '/caixas/retorno',
  path: '/caixas/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasInventarioRoute = CaixasInventarioRouteImport.update({
  id: '/caixas/inventario',
  path: '/caixas/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasGalpaoRoute = CaixasGalpaoRouteImport.update({
  id: '/caixas/galpao',
  path: '/caixas/galpao',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasFornecedorRoute = CaixasFornecedorRouteImport.update({
  id: '/caixas/fornecedor',
  path: '/caixas/fornecedor',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasEconomiaRoute = CaixasEconomiaRouteImport.update({
  id: '/caixas/economia',
  path: '/caixas/economia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedor': typeof FornecedorRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/fornecedor': typeof CaixasFornecedorRoute
  '/caixas/galpao': typeof CaixasGalpaoRoute
  '/caixas/inventario': typeof CaixasInventarioRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/quebra/lancar': typeof QuebraLancarRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/recebimento/liberacoes': typeof RecebimentoLiberacoesRoute
  '/recebimento/vales': typeof RecebimentoValesRoute
  '/expedicao/': typeof ExpedicaoIndexRoute
  '/quebra/': typeof QuebraIndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedor': typeof FornecedorRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/fornecedor': typeof CaixasFornecedorRoute
  '/caixas/galpao': typeof CaixasGalpaoRoute
  '/caixas/inventario': typeof CaixasInventarioRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/quebra/lancar': typeof QuebraLancarRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/recebimento/liberacoes': typeof RecebimentoLiberacoesRoute
  '/recebimento/vales': typeof RecebimentoValesRoute
  '/expedicao': typeof ExpedicaoIndexRoute
  '/quebra': typeof QuebraIndexRoute
  '/recebimento': typeof RecebimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fornecedor': typeof FornecedorRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/fornecedor': typeof CaixasFornecedorRoute
  '/caixas/galpao': typeof CaixasGalpaoRoute
  '/caixas/inventario': typeof CaixasInventarioRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/quebra/lancar': typeof QuebraLancarRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/recebimento/liberacoes': typeof RecebimentoLiberacoesRoute
  '/recebimento/vales': typeof RecebimentoValesRoute
  '/expedicao/': typeof ExpedicaoIndexRoute
  '/quebra/': typeof QuebraIndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fornecedor'
    | '/fornecedores'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/fornecedor'
    | '/caixas/galpao'
    | '/caixas/inventario'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/quebra/lancar'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/recebimento/liberacoes'
    | '/recebimento/vales'
    | '/expedicao/'
    | '/quebra/'
    | '/recebimento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fornecedor'
    | '/fornecedores'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/fornecedor'
    | '/caixas/galpao'
    | '/caixas/inventario'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/quebra/lancar'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/recebimento/liberacoes'
    | '/recebimento/vales'
    | '/expedicao'
    | '/quebra'
    | '/recebimento'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fornecedor'
    | '/fornecedores'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/fornecedor'
    | '/caixas/galpao'
    | '/caixas/inventario'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/quebra/lancar'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/recebimento/liberacoes'
    | '/recebimento/vales'
    | '/expedicao/'
    | '/quebra/'
    | '/recebimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FornecedorRoute: typeof FornecedorRoute
  FornecedoresRoute: typeof FornecedoresRoute
  GestaoRoute: typeof GestaoRouteWithChildren
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  CaixasEconomiaRoute: typeof CaixasEconomiaRoute
  CaixasFornecedorRoute: typeof CaixasFornecedorRoute
  CaixasGalpaoRoute: typeof CaixasGalpaoRoute
  CaixasInventarioRoute: typeof CaixasInventarioRoute
  CaixasRetornoRoute: typeof CaixasRetornoRoute
  CaixasSaldoRoute: typeof CaixasSaldoRoute
  ExpedicaoTvRoute: typeof ExpedicaoTvRoute
  QuebraLancarRoute: typeof QuebraLancarRoute
  RecebimentoConferirRoute: typeof RecebimentoConferirRoute
  RecebimentoFaltasRoute: typeof RecebimentoFaltasRoute
  RecebimentoLiberacoesRoute: typeof RecebimentoLiberacoesRoute
  RecebimentoValesRoute: typeof RecebimentoValesRoute
  ExpedicaoIndexRoute: typeof ExpedicaoIndexRoute
  QuebraIndexRoute: typeof QuebraIndexRoute
  RecebimentoIndexRoute: typeof RecebimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor': {
      id: '/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof FornecedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/': {
      id: '/recebimento/'
      path: '/recebimento'
      fullPath: '/recebimento/'
      preLoaderRoute: typeof RecebimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quebra/': {
      id: '/quebra/'
      path: '/quebra'
      fullPath: '/quebra/'
      preLoaderRoute: typeof QuebraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicao/': {
      id: '/expedicao/'
      path: '/expedicao'
      fullPath: '/expedicao/'
      preLoaderRoute: typeof ExpedicaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/vales': {
      id: '/recebimento/vales'
      path: '/recebimento/vales'
      fullPath: '/recebimento/vales'
      preLoaderRoute: typeof RecebimentoValesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/liberacoes': {
      id: '/recebimento/liberacoes'
      path: '/recebimento/liberacoes'
      fullPath: '/recebimento/liberacoes'
      preLoaderRoute: typeof RecebimentoLiberacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/faltas': {
      id: '/recebimento/faltas'
      path: '/recebimento/faltas'
      fullPath: '/recebimento/faltas'
      preLoaderRoute: typeof RecebimentoFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/conferir': {
      id: '/recebimento/conferir'
      path: '/recebimento/conferir'
      fullPath: '/recebimento/conferir'
      preLoaderRoute: typeof RecebimentoConferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quebra/lancar': {
      id: '/quebra/lancar'
      path: '/quebra/lancar'
      fullPath: '/quebra/lancar'
      preLoaderRoute: typeof QuebraLancarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/usuarios': {
      id: '/gestao/usuarios'
      path: '/usuarios'
      fullPath: '/gestao/usuarios'
      preLoaderRoute: typeof GestaoUsuariosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/expedicao/tv': {
      id: '/expedicao/tv'
      path: '/expedicao/tv'
      fullPath: '/expedicao/tv'
      preLoaderRoute: typeof ExpedicaoTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/saldo': {
      id: '/caixas/saldo'
      path: '/caixas/saldo'
      fullPath: '/caixas/saldo'
      preLoaderRoute: typeof CaixasSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/retorno': {
      id: '/caixas/retorno'
      path: '/caixas/retorno'
      fullPath: '/caixas/retorno'
      preLoaderRoute: typeof CaixasRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/inventario': {
      id: '/caixas/inventario'
      path: '/caixas/inventario'
      fullPath: '/caixas/inventario'
      preLoaderRoute: typeof CaixasInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/galpao': {
      id: '/caixas/galpao'
      path: '/caixas/galpao'
      fullPath: '/caixas/galpao'
      preLoaderRoute: typeof CaixasGalpaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/fornecedor': {
      id: '/caixas/fornecedor'
      path: '/caixas/fornecedor'
      fullPath: '/caixas/fornecedor'
      preLoaderRoute: typeof CaixasFornecedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/economia': {
      id: '/caixas/economia'
      path: '/caixas/economia'
      fullPath: '/caixas/economia'
      preLoaderRoute: typeof CaixasEconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GestaoRouteChildren {
  GestaoUsuariosRoute: typeof GestaoUsuariosRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoUsuariosRoute: GestaoUsuariosRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FornecedorRoute: FornecedorRoute,
  FornecedoresRoute: FornecedoresRoute,
  GestaoRoute: GestaoRouteWithChildren,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  CaixasEconomiaRoute: CaixasEconomiaRoute,
  CaixasFornecedorRoute: CaixasFornecedorRoute,
  CaixasGalpaoRoute: CaixasGalpaoRoute,
  CaixasInventarioRoute: CaixasInventarioRoute,
  CaixasRetornoRoute: CaixasRetornoRoute,
  CaixasSaldoRoute: CaixasSaldoRoute,
  ExpedicaoTvRoute: ExpedicaoTvRoute,
  QuebraLancarRoute: QuebraLancarRoute,
  RecebimentoConferirRoute: RecebimentoConferirRoute,
  RecebimentoFaltasRoute: RecebimentoFaltasRoute,
  RecebimentoLiberacoesRoute: RecebimentoLiberacoesRoute,
  RecebimentoValesRoute: RecebimentoValesRoute,
  ExpedicaoIndexRoute: ExpedicaoIndexRoute,
  QuebraIndexRoute: QuebraIndexRoute,
  RecebimentoIndexRoute: RecebimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
