/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentoIndexRouteImport } from './routes/recebimento/index'
import { Route as ExpedicaoIndexRouteImport } from './routes/expedicao/index'
import { Route as RecebimentoFaltasRouteImport } from './routes/recebimento/faltas'
import { Route as RecebimentoConferirRouteImport } from './routes/recebimento/conferir'
import { Route as GestaoUsuariosRouteImport } from './routes/gestao.usuarios'
import { Route as ExpedicaoTvRouteImport } from './routes/expedicao/tv'
import { Route as CaixasSaldoRouteImport } from './routes/caixas/saldo'
import { Route as CaixasRetornoRouteImport } from './routes/caixas/retorno'
import { Route as CaixasEconomiaRouteImport } from './routes/caixas/economia'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoIndexRoute = RecebimentoIndexRouteImport.update({
  id: '/recebimento/',
  path: '/recebimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicaoIndexRoute = ExpedicaoIndexRouteImport.update({
  id: '/expedicao/',
  path: '/expedicao/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoFaltasRoute = RecebimentoFaltasRouteImport.update({
  id: '/recebimento/faltas',
  path: '/recebimento/faltas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoConferirRoute = RecebimentoConferirRouteImport.update({
  id: '/recebimento/conferir',
  path: '/recebimento/conferir',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoUsuariosRoute = GestaoUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GestaoRoute,
} as any)
const ExpedicaoTvRoute = ExpedicaoTvRouteImport.update({
  id: '/expedicao/tv',
  path: '/expedicao/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasSaldoRoute = CaixasSaldoRouteImport.update({
  id: '/caixas/saldo',
  path: '/caixas/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasRetornoRoute = CaixasRetornoRouteImport.update({
  id: '/caixas/retorno',
  path: '/caixas/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixasEconomiaRoute = CaixasEconomiaRouteImport.update({
  id: '/caixas/economia',
  path: '/caixas/economia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/expedicao/': typeof ExpedicaoIndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/expedicao': typeof ExpedicaoIndexRoute
  '/recebimento': typeof RecebimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/caixas/economia': typeof CaixasEconomiaRoute
  '/caixas/retorno': typeof CaixasRetornoRoute
  '/caixas/saldo': typeof CaixasSaldoRoute
  '/expedicao/tv': typeof ExpedicaoTvRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/recebimento/conferir': typeof RecebimentoConferirRoute
  '/recebimento/faltas': typeof RecebimentoFaltasRoute
  '/expedicao/': typeof ExpedicaoIndexRoute
  '/recebimento/': typeof RecebimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/expedicao/'
    | '/recebimento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/expedicao'
    | '/recebimento'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gestao'
    | '/indicadores'
    | '/login'
    | '/caixas/economia'
    | '/caixas/retorno'
    | '/caixas/saldo'
    | '/expedicao/tv'
    | '/gestao/usuarios'
    | '/recebimento/conferir'
    | '/recebimento/faltas'
    | '/expedicao/'
    | '/recebimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GestaoRoute: typeof GestaoRouteWithChildren
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  CaixasEconomiaRoute: typeof CaixasEconomiaRoute
  CaixasRetornoRoute: typeof CaixasRetornoRoute
  CaixasSaldoRoute: typeof CaixasSaldoRoute
  ExpedicaoTvRoute: typeof ExpedicaoTvRoute
  RecebimentoConferirRoute: typeof RecebimentoConferirRoute
  RecebimentoFaltasRoute: typeof RecebimentoFaltasRoute
  ExpedicaoIndexRoute: typeof ExpedicaoIndexRoute
  RecebimentoIndexRoute: typeof RecebimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/': {
      id: '/recebimento/'
      path: '/recebimento'
      fullPath: '/recebimento/'
      preLoaderRoute: typeof RecebimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicao/': {
      id: '/expedicao/'
      path: '/expedicao'
      fullPath: '/expedicao/'
      preLoaderRoute: typeof ExpedicaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/faltas': {
      id: '/recebimento/faltas'
      path: '/recebimento/faltas'
      fullPath: '/recebimento/faltas'
      preLoaderRoute: typeof RecebimentoFaltasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento/conferir': {
      id: '/recebimento/conferir'
      path: '/recebimento/conferir'
      fullPath: '/recebimento/conferir'
      preLoaderRoute: typeof RecebimentoConferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/usuarios': {
      id: '/gestao/usuarios'
      path: '/usuarios'
      fullPath: '/gestao/usuarios'
      preLoaderRoute: typeof GestaoUsuariosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/expedicao/tv': {
      id: '/expedicao/tv'
      path: '/expedicao/tv'
      fullPath: '/expedicao/tv'
      preLoaderRoute: typeof ExpedicaoTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/saldo': {
      id: '/caixas/saldo'
      path: '/caixas/saldo'
      fullPath: '/caixas/saldo'
      preLoaderRoute: typeof CaixasSaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/retorno': {
      id: '/caixas/retorno'
      path: '/caixas/retorno'
      fullPath: '/caixas/retorno'
      preLoaderRoute: typeof CaixasRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixas/economia': {
      id: '/caixas/economia'
      path: '/caixas/economia'
      fullPath: '/caixas/economia'
      preLoaderRoute: typeof CaixasEconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GestaoRouteChildren {
  GestaoUsuariosRoute: typeof GestaoUsuariosRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoUsuariosRoute: GestaoUsuariosRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GestaoRoute: GestaoRouteWithChildren,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  CaixasEconomiaRoute: CaixasEconomiaRoute,
  CaixasRetornoRoute: CaixasRetornoRoute,
  CaixasSaldoRoute: CaixasSaldoRoute,
  ExpedicaoTvRoute: ExpedicaoTvRoute,
  RecebimentoConferirRoute: RecebimentoConferirRoute,
  RecebimentoFaltasRoute: RecebimentoFaltasRoute,
  ExpedicaoIndexRoute: ExpedicaoIndexRoute,
  RecebimentoIndexRoute: RecebimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
